### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lisaover** [andrew-hossack/dash-tools#123]
Thank you so much for helping improve the quality of dash-tools!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

- replace the result of `dash-tools --version` below

```
1.12.0
```

- please tell us what operating system you are using

```
mac os 15.4.1
```

**Describe the bug**

I am getting the error: "AttributeError: module 'dash.development' has no attribute 'component_loader'" when i run 'dashtool gui'. I have the 3.0.4 version of dash installed. I checked the dash.development library for the component_loader file, but it does not exist. There is a component_generator...not sure if that is an upgrade from component_loader. I tried going back to version 2.18.2 of dash per a forum response, but that then requires going back to earlier versions of dash_bootstrap_components, among others. Are you planning on updating dash-tools so that it will work with the 3.0.4 version of dash?

**Expected behavior**

I expected dash-tools to assist me in deploying my app by running without this error. Thank you for your consideration.

**Screenshots**

If applicable, add screenshots or screen recording to help explain your problem.

**Comment by saiffanwar** [comment]
I'm also experiencing this issue with dash tools 1.12.0 and Linux mint 22.1 Cinnamon. My Python version is 3.12.3

Did you find a fix for this @lisaover ?
